### ISSUE TITLE
Consistent results ? 

### ISSUE THREAD

**Issue by MoMe36** [nikhilbarhate99/TD3-PyTorch-BipedalWalker-v2#2]
Hey ! Thanks for open-sourcing your implementation, it's good to see RL examples in PyTorch. 

I've been using your work for some tests and I wanted to know how consistent was your policy ? I mean, it sometimes trains successfully while in some runs completely fails.  

![seed_0](https://user-images.githubusercontent.com/18698421/50471722-45210300-09b6-11e9-8111-27299580503e.png)

![seed_1](https://user-images.githubusercontent.com/18698421/50471733-4d793e00-09b6-11e9-9cb2-a52c5d8840d8.png)

![seed_2](https://user-images.githubusercontent.com/18698421/50471742-536f1f00-09b6-11e9-93c9-73111a9b2b3c.png)

![seed_3](https://user-images.githubusercontent.com/18698421/50471751-5b2ec380-09b6-11e9-8167-005766a22015.png)

What do you think ? 

Thanks (:

**Comment by nikhilbarhate99** [comment]
Hey ! Thanks for running the tests :)  I have not been able to test it multiple times, since I am currently using a dual core machine, so it takes forever to train. Still I trained it 4 to 5 times (without seeding) and it worked two times (there are 2 trained models in the preTrained folder), so I thought maybe its working, perhaps that explains why its taking so long for the hardcore version.
